
def set_shapes(widget_id):
    shape_index = ["cheekPuffLeft", "cheekPuffRight", "cheekSuckLeft", "cheekSuckRight", "jawOpen", "jawForward", "jawLeft", "jawRight", "noseSneerLeft", "noseSneerRight", "mouthFunnel", "mouthPucker", "mouthLeft", "mouthRight", 
    "mouthRollUpper", "mouthRollLower", "mouthShrugUpper", "mouthShrugLower", "mouthClose", "mouthSmileLeft", 
    "mouthSmileRight", "mouthFrownLeft", "mouthFrownRight", "mouthDimpleLeft", "mouthDimpleRight", "mouthUpperUpLeft", 
    "mouthUpperUpRight", "mouthLowerDownLeft", "mouthLowerDownRight", "mouthPressLeft", "mouthPressRight", "mouthStretchLeft", 
    "mouthStretchRight", "tongueOut", "tongueUp", "tongueDown", "tongueLeft", "tongueRight", "tongueRoll", "tongueBendDown", "tongueCurlUp", "tongueSquish", "tongueFlat", "tongueTwistLeft", "tongueTwistRight"]
    
    shape = [
        [
        f"-CHEEKPUFFLEFTMIN{widget_id}-",
        f"-CHEEKPUFFRIGHTMIN{widget_id}-",
        f"-CHEEKSUCKLEFTMIN{widget_id}-",
        f"-CHEEKSUCKRIGHTMIN{widget_id}-",
        f"-JAWOPENMIN{widget_id}-",
        f"-JAWFORWARDMIN{widget_id}-",
        f"-JAWLEFTMIN{widget_id}-",
        f"-JAWRIGHTMIN{widget_id}-",
        f"-NOSESNEERLEFTMIN{widget_id}-",
        f"-NOSESNEERRIGHTMIN{widget_id}-",
        f"-MOUTHFUNNELMIN{widget_id}-",
        f"-MOUTHPUCKERMIN{widget_id}-",
        f"-MOUTHLEFTMIN{widget_id}-",
        f"-MOUTHRIGHTMIN{widget_id}-",
        f"-MOUTHROLLUPPERMIN{widget_id}-",
        f"-MOUTHROLLLOWERMIN{widget_id}-",
        f"-MOUTHSHRUGUPPERMIN{widget_id}-",
        f"-MOUTHSHRUGLOWERMIN{widget_id}-",
        f"-MOUTHCLOSEMIN{widget_id}-",
        f"-MOUTHSMILELEFTMIN{widget_id}-",
        f"-MOUTHSMILERIGHTMIN{widget_id}-",
        f"-MOUTHFROWNLEFTMIN{widget_id}-",
        f"-MOUTHFROWNRIGHTMIN{widget_id}-",
        f"-MOUTHDIMPLELEFTMIN{widget_id}-",
        f"-MOUTHDIMPLERIGHTMIN{widget_id}-",
        f"-MOUTHUPPERUPLEFTMIN{widget_id}-",
        f"-MOUTHUPPERUPRIGHTMIN{widget_id}-",
        f"-MOUTHLOWERDOWNLEFTMIN{widget_id}-",
        f"-MOUTHLOWERDOWNRIGHTMIN{widget_id}-",
        f"-MOUTHPRESSLEFTMIN{widget_id}-",
        f"-MOUTHPRESSRIGHTMIN{widget_id}-",
        f"-MOUTHSTRETCHLEFTMIN{widget_id}-",
        f"-MOUTHSTRETCHRIGHTMIN{widget_id}-",
        f"-TONGUEOUTMIN{widget_id}-",
        f"-TONGUEUPMIN{widget_id}-",
        f"-TONGUEDOWNMIN{widget_id}-",
        f"-TONGUELEFTMIN{widget_id}-",
        f"-TONGUERIGHTMIN{widget_id}-",
        f"-TONGUEROLLMIN{widget_id}-",
        f"-TONGUEBENDDOWNMIN{widget_id}-",
        f"-TONGUECURLUPMIN{widget_id}-",
        f"-TONGUESQUISHMIN{widget_id}-",
        f"-TONGUEFLATMIN{widget_id}-",
        f"-TONGUETWISTLEFTMIN{widget_id}-",
        f"-TONGUETWISTRIGHTMIN{widget_id}-",
        ],
        [
        f"-CHEEKPUFFLEFTMAX{widget_id}-",
        f"-CHEEKPUFFRIGHTMAX{widget_id}-",
        f"-CHEEKSUCKLEFTMAX{widget_id}-",
        f"-CHEEKSUCKRIGHTMAX{widget_id}-",
        f"-JAWOPENMAX{widget_id}-",
        f"-JAWFORWARDMAX{widget_id}-",
        f"-JAWLEFTMAX{widget_id}-",
        f"-JAWRIGHTMAX{widget_id}-",
        f"-NOSESNEERLEFTMAX{widget_id}-",
        f"-NOSESNEERRIGHTMAX{widget_id}-",
        f"-MOUTHFUNNELMAX{widget_id}-",
        f"-MOUTHPUCKERMAX{widget_id}-",
        f"-MOUTHLEFTMAX{widget_id}-",
        f"-MOUTHRIGHTMAX{widget_id}-",
        f"-MOUTHROLLUPPERMAX{widget_id}-",
        f"-MOUTHROLLLOWERMAX{widget_id}-",
        f"-MOUTHSHRUGUPPERMAX{widget_id}-",
        f"-MOUTHSHRUGLOWERMAX{widget_id}-",
        f"-MOUTHCLOSEMAX{widget_id}-",
        f"-MOUTHSMILELEFTMAX{widget_id}-",
        f"-MOUTHSMILERIGHTMAX{widget_id}-",
        f"-MOUTHFROWNLEFTMAX{widget_id}-",
        f"-MOUTHFROWNRIGHTMAX{widget_id}-",
        f"-MOUTHDIMPLELEFTMAX{widget_id}-",
        f"-MOUTHDIMPLERIGHTMAX{widget_id}-",
        f"-MOUTHUPPERUPLEFTMAX{widget_id}-",
        f"-MOUTHUPPERUPRIGHTMAX{widget_id}-",
        f"-MOUTHLOWERDOWNLEFTMAX{widget_id}-",
        f"-MOUTHLOWERDOWNRIGHTMAX{widget_id}-",
        f"-MOUTHPRESSLEFTMAX{widget_id}-",
        f"-MOUTHPRESSRIGHTMAX{widget_id}-",
        f"-MOUTHSTRETCHLEFTMAX{widget_id}-",
        f"-MOUTHSTRETCHRIGHTMAX{widget_id}-",
        f"-TONGUEOUTMAX{widget_id}-",
        f"-TONGUEUPMAX{widget_id}-",
        f"-TONGUEDOWNMAX{widget_id}-",
        f"-TONGUELEFTMAX{widget_id}-",
        f"-TONGUERIGHTMAX{widget_id}-",
        f"-TONGUEROLLMAX{widget_id}-",
        f"-TONGUEBENDDOWNMAX{widget_id}-",
        f"-TONGUECURLUPMAX{widget_id}-",
        f"-TONGUESQUISHMAX{widget_id}-",
        f"-TONGUEFLATMAX{widget_id}-",
        f"-TONGUETWISTLEFTMAX{widget_id}-",
        f"-TONGUETWISTRIGHTMAX{widget_id}-",
        ],

    ]
    return shape_index, shape


